# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 10:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dkapp', '0002_auto_20170830_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kharj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tozih', models.CharField(max_length=100)),
                ('tarikh', models.DateTimeField()),
                ('mablagh', models.BigIntegerField()),
                ('nam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
