# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dkapp', '0003_kharj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='token',
            new_name='ramz',
        ),
    ]
